# lib/reporting.sh
# Reporting library for devbox diagnostics

mkdir -p "$SCRIPT_DIR/diagnostic_reports"
reportfile="$SCRIPT_DIR/diagnostic_reports/report-$TIMESTAMP.log"

report_header() {
    echo "Diagnostic Report - $TIMESTAMP" > "$reportfile"
    echo "Generated by devbox diagnostics" >> "$reportfile"
    echo "======================================" >> "$reportfile"
    log INFO "Diagnostic report initialized at $reportfile"
}

report_header

report() {
    report_level=$1
    shift
    local message=$@
    echo "$message"
    
    log LOG "Report entry at level $report_level: $message"
    echo "[$report_level] $message" >> "$reportfile"

}
