# lib/reporting.sh
# Reporting library for devbox diagnostics


archive_old_reports() {
    log DEBUG "Archiving old diagnostic reports"
    local archive_dir="$SCRIPT_DIR/diagnostic_reports/archive"
    mkdir -p "$archive_dir"
    find "$SCRIPT_DIR/diagnostic_reports" -maxdepth 1 -type f -name "report-*.log" -exec mv {} "$archive_dir/" \;
    log INFO "Old diagnostic reports archived to $archive_dir"
}
report_header() {
    echo "Diagnostic Report - $TIMESTAMP" > "$reportfile"
    echo "Generated by devbox diagnostics" >> "$reportfile"
    echo "======================================" >> "$reportfile"
    log INFO "Diagnostic report initialized at $reportfile"
}

init_reporting() {
    mkdir -p "$SCRIPT_DIR/diagnostic_reports"
    reportfile="$SCRIPT_DIR/diagnostic_reports/report-$(date +%Y-%m-%d-%H-%M-%S).log"
    archive_old_reports
    report_header
}

report() {
    local report_level=$1
    shift
    local message=$*
    #echo "$message"
    
    log "$report_level" "$message"
    echo "[$report_level] $message" >> "$reportfile"
    echo "$message"

}
